// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdybfpcithikkfozmeft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1keWJmcGNpdGhpa2tmb3ptZWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzcxNzEsImV4cCI6MjA2MjY1MzE3MX0.oo7hFKf1vRWWkDweiZKODsdoltDot9199iXrFiZPrqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);